#!/usr/bin/env bash

# Check if the number of arguments passed is less than 4, display usage and exit
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Set the parameters
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i $path_to_ssh_key $path_to_file $username@$ip:~/

# Check if the transfer was successful
if [ $? -eq 0 ]; then
  echo "File transferred successfully to $ip"
else
  echo "Error transferring file to $ip"
  exit 1
fi

exit 0

