#!/usr/bin/env bash
sudo bash -c "cat > /etc/nginx/conf.d/redirect_me.conf << EOF
server {
    listen 80;
    server_name example.com;

    location /redirect_me {
        return 301 https://example.com/new_page;
    }
}
EOF"

