#!/usr/bin/env bash
sudo bash -c "cat > /etc/nginx/conf.d/custom_404.conf << EOF
server {
    listen 80;
    server_name example.com;

    error_page 404 /404.html;
    location = /404.html {
        internal;
        root /usr/share/nginx/html;
        echo 'Ceci n\'est pas une page';
    }
}
EOF"

